repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Run ruff check
        entry: poetry run just check
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: pytest
        name: Run pytest
        entry: poetry run just test
        language: system
        pass_filenames: false
        stages: [pre-commit]